--------------------------------------------------------------
 --     Copyright (c) 2012-2024 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/lab202509/al56_detect/al_ip/clk_pll.vhd
 -- Date	:	2025 10 07
 -- TD version	:	5.6.119222
--------------------------------------------------------------

-------------------------------------------------------------------------------
--	Input frequency:               50.000000MHz
--	Clock multiplication factor: 1
--	Clock division factor:       4
--	Clock information:
--		Clock name	| Frequency 	| Phase shift
--		C0        	| 12.500000 MHZ	| 0.0000  DEG  
--		C1        	| 125.000000MHZ	| 0.0000  DEG  
--		C2        	| 125.000000MHZ	| 180.0000 DEG  
-------------------------------------------------------------------------------

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
USE ieee.std_logic_unsigned.ALL;
USE ieee.std_logic_arith.ALL;
LIBRARY eagle_macro;
USE eagle_macro.EAGLE_COMPONENTS.ALL;

ENTITY clk_pll IS
  PORT (
    refclk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    extlock : OUT STD_LOGIC;
    clk0_out : OUT STD_LOGIC;
    clk1_out : OUT STD_LOGIC;
    clk2_out : OUT STD_LOGIC 
  );
END clk_pll;

ARCHITECTURE rtl OF clk_pll IS
  SIGNAL clk0_buf :  STD_LOGIC;
  SIGNAL fbk_wire :  STD_LOGIC;
  SIGNAL clkc_wire :  STD_LOGIC_VECTOR (4 DOWNTO 0);
BEGIN
  bufg_feedback : EG_LOGIC_BUFG
  PORT MAP (
    i => clk0_buf,
    o => fbk_wire 
  );

  pll_inst : EG_PHY_PLL
  GENERIC MAP (
    DPHASE_SOURCE => "DISABLE",
    DYNCFG => "DISABLE",
    FIN => "50.000000",
    FEEDBK_MODE => "NORMAL",
    FEEDBK_PATH => "CLKC0_EXT",
    STDBY_ENABLE => "DISABLE",
    PLLRST_ENA => "ENABLE",
    SYNC_ENABLE => "DISABLE",
    GMC_GAIN => 0,
    ICP_CURRENT => 9,
    KVCO => 2,
    LPF_CAPACITOR => 2,
    LPF_RESISTOR => 8,
    REFCLK_DIV => 4,
    FBCLK_DIV => 1,
    CLKC0_ENABLE => "ENABLE",
    CLKC0_DIV => 80,
    CLKC0_CPHASE => 79,
    CLKC0_FPHASE => 0,
    CLKC1_ENABLE => "ENABLE",
    CLKC1_DIV => 8,
    CLKC1_CPHASE => 7,
    CLKC1_FPHASE => 0,
    CLKC2_ENABLE => "ENABLE",
    CLKC2_DIV => 8,
    CLKC2_CPHASE => 3,
    CLKC2_FPHASE => 0 
  )
  PORT MAP (
    refclk => refclk,
    reset => reset,
    stdby => '0',
    extlock => extlock,
    load_reg => '0',
    psclk => '0',
    psdown => '0',
    psstep => '0',
    psclksel => b"000",
    dclk => '0',
    dcs => '0',
    dwe => '0',
    di => b"00000000",
    daddr => b"000000",
    fbclk => fbk_wire,
    clkc => clkc_wire 
  );

  clk0_out <= fbk_wire;
  clk2_out <= clkc_wire(2);
  clk1_out <= clkc_wire(1);
  clk0_buf <= clkc_wire(0);

END rtl;

