--------------------------------------------------------------
 --     Copyright (c) 2012-2024 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/lab202509/al56/al_ip/oddr123.vhd
 -- Date	:	2025 10 02
 -- TD version	:	5.6.119222
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY oddr123 IS
PORT (
	q	: OUT STD_LOGIC;
	clk	: IN STD_LOGIC;
	d1	: IN STD_LOGIC;
	d0	: IN STD_LOGIC;
	rst	: IN STD_LOGIC
	);
END oddr123;

ARCHITECTURE struct OF oddr123 IS

	BEGIN
	inst : EG_LOGIC_ODDR
		GENERIC MAP (
			ASYNCRST	=> "ENABLE"
		)
		PORT MAP (
			q	=> q,
			clk	=> clk,
			d1	=> d1,
			d0	=> d0,
			rst	=> rst
		);

END struct;
